### ISSUE TITLE
Check argument order

### ISSUE THREAD

**Issue by StanWijn** [smartdata-analysis-and-statistics/precmed#38]
After we restructured the function arguments to prioritize mandatory over optional arguments (moved to the front), there is a mismatch between the order in the function and the help file & examples. 

I have already restructured the outputs_main() file, but we need to check all the other files to make sure consistancy with the function, helpfiles, examples and vignettes. 

Note: the vignettes all match the new structure already

**Comment by NightlordTW** [comment]
@jcaldasmagalhaes I'm picking up this issue as I still need to make some other revisions before submitting the package
