### ISSUE TITLE
Revise Count-examples

### ISSUE THREAD

**Issue by NightlordTW** [smartdata-analysis-and-statistics/precmed#47]
It would be helpful to restructure the example section as follows:

1. Introduction of the example (please add a baseline table)
2. Estimation of avarage treatment effect (atefit) => introduce concept of confounding adjustment (formula PS with logistic regression), prognostic prediction (formula for y; use of Poisson regression; and some explanaition why we are adjusting for prognostic covariates when estimating the ATE), need for bootstrapping when estimating standard error.  
3. Estimation of individual treatment effect (catefit) . Explain what kind of ITE model is being estimated; how do we allow for treatment-covariate interaction?
4. Internal validation (catecv): Why do we need it? What can we compare? What is the output?

Source: https://github.com/smartdata-analysis-and-statistics/precmed/blob/main/vignettes/Count-examples.Rmd

**Comment by StanWijn** [comment]
Resolved in recent commits
