### ISSUE TITLE
Implement feedback on the vignettes

### ISSUE THREAD

**Issue by NightlordTW** [smartdata-analysis-and-statistics/precmed#51]
- [ ] https://smartdata-analysis-and-statistics.github.io/precmed/index.html
- [ ] https://smartdata-analysis-and-statistics.github.io/precmed/articles/precmed.html
- [ ] https://smartdata-analysis-and-statistics.github.io/precmed/articles/Count-examples.html
- [ ] https://smartdata-analysis-and-statistics.github.io/precmed/articles/Survival-examples.html

**Comment by StanWijn** [comment]
Resolved in recent commits
